version: 0.2
phases:
  install:
    commands:
      - echo Date before `date`
      - apk add tzdata && ls /usr/share/zoneinfo
      - cp /usr/share/zoneinfo/Europe/Brussels /etc/localtime
      - echo "Europe/Brussels" >  /etc/timezone
      - echo Date after `date`
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`