version: 0.2
phases:
  install:
    commands:
      - echo Date before `date`
      - export TZ=Asia/Singapore
      - echo Date after `date`
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`